/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  EthosSphereRegistry,
  EthosSphereRegistryInterface,
} from "../EthosSphereRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newScore",
        type: "uint256",
      },
    ],
    name: "ScoreUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "profiles",
    outputs: [
      {
        internalType: "uint256",
        name: "ethosScore",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "benefitTier",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "penaltyLevel",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "recoveryStage",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "newScore",
        type: "uint256",
      },
    ],
    name: "updateScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102fd806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806365d977241461003b578063bbe1562714610057575b600080fd5b610055600480360381019061005091906101eb565b61008a565b005b610071600480360381019061006c919061022b565b610122565b6040516100819493929190610267565b60405180910390f35b806000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600001819055508173ffffffffffffffffffffffffffffffffffffffff167f66ead48cfe0e1d1aa8bad492e906c348dfcfeecbf3b7b2cdf9b1f3cfa42a29458260405161011691906102ac565b60405180910390a25050565b60006020528060005260406000206000915090508060000154908060010154908060020154908060030154905084565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061018282610157565b9050919050565b61019281610177565b811461019d57600080fd5b50565b6000813590506101af81610189565b92915050565b6000819050919050565b6101c8816101b5565b81146101d357600080fd5b50565b6000813590506101e5816101bf565b92915050565b6000806040838503121561020257610201610152565b5b6000610210858286016101a0565b9250506020610221858286016101d6565b9150509250929050565b60006020828403121561024157610240610152565b5b600061024f848285016101a0565b91505092915050565b610261816101b5565b82525050565b600060808201905061027c6000830187610258565b6102896020830186610258565b6102966040830185610258565b6102a36060830184610258565b95945050505050565b60006020820190506102c16000830184610258565b9291505056fea2646970667358221220e57796a32d770d66d77a3cb8f0152695a3fa946bd4257baf712e7e817b5b52e464736f6c63430008180033";

type EthosSphereRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthosSphereRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthosSphereRegistry__factory extends ContractFactory {
  constructor(...args: EthosSphereRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EthosSphereRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): EthosSphereRegistry__factory {
    return super.connect(runner) as EthosSphereRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthosSphereRegistryInterface {
    return new Interface(_abi) as EthosSphereRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EthosSphereRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as EthosSphereRegistry;
  }
}
