/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthosSphereRegistry } from "./EthosSphereRegistry";
export * as factories from "./factories";
export { EthosSphereRegistry__factory } from "./factories/EthosSphereRegistry__factory";
